### ISSUE TITLE
play around with "coder-toolset" and find things todo ...

### ISSUE THREAD

**Issue by hrbu** [cubbles/coder-toolset#2]
The current version of the "coder-toolset" is on development state. Please play around with it and create a list with things we need to work on ...

## Acceptance Criterias
- [ ] This ticket contains a list of "things to do"

**Comment by edwingamboa** [comment]
The `coder-toolset` (mainly the `coder-template` scripts). All scripts except `upload:dev` and `open` worked. It was not possible to test the components working and use dependencies since the components are rendered as text. It should be due to the use of "@" and "/" for the tag name (See [this](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) and [this](https://www.utf8-chartable.de/unicode-utf8-table.pl?number=1024&names=-&unicodeinhtml=hex)). 

The following issues were identified:

#### Testing components
* [x] Downloaded coder-template has the manifest with upper case name MANIFEST: /home/edwin/Documents/incowia/coder-toolset/node_modules/webpack-cli/bin/cli.js:244 throws an error in Linux (case sensitive)
* [x] SHOWROOM.html files, also case sensitive for paths in Linux
* [ ] Not a success message after running build (It would be nice to have a message indicating that everything went well or showing an error message (if any))
* [ ] Serve command: browser does not start as in grunt task
* [x] Component tags are recognised as text (@ and / cannot be used for tag names)
* [x] We use @ to separate webpackageId from version
* [x] Component dependencies defined in manifest are not served since no component is identified
* [ ] manifest scripts has an error in [this line](https://github.com/cubbles/coder-toolset/blob/38fd9ae7abc2253bbc9ead62e21ea965e5668af0/packages/wpkg-utils/lib/getManifestWebpackage.js#L33). It uses 'MANIIFEST' instead off 'manifest' in the findRegex regular experession. Thus, artifacts are not added to the manifest of the build folder (at least in Linux).
* [ ] The manifest of the sample utitlity is neaing generated using UPPERCASE name (i.e. MANIFEST.utility.js)
 
#### UPLOAD
* [x] Uploader looks for manifest.webpackage and not MANIFEST.wepackage (Linux is case sensitive)
* [ ] Uploader looks for the manifest file in root folder of the webpackage ane not in dist folder
* [ ] Config from cubx-uploader-config.dev.json is ignored by configProvider (e.g. "source": "./_dist property is not taken into account)
* [ ] Default source value (./_dist) is invalid, it should be ./dist
* [x] ./dist is invalid, because manifest.webpackage is not in root of this folder of cubx-uploader-config files

#### Testing components
* [ ] Although the sample elementary component works as expected, an error log is shown in the console saying that the CubxComponent object was not found.
* [x] All sample artifacts work as expected
* [ ] The watch script does not reflect changes from individual artifacts into the final manofest.webpackage file of the dist folder

#### Other scripts
* [ ] npm run open, does not work. Thus, neither all the scripts that use it do it. (I don't understand how to use it properly)

#### Explain Initial steps (or provide links to the info)
* [x] Compose initial steps guide 
* [x] Explain that scripts should be run with yarn (at least install)
* [ ] Explain that one should navigate to the corresponding package to run scripts; e.g., coder-template package to run commands

**Comment by hrbu** [comment]
Thanks Edwin!

> Component tags are recognised as text (@ and / canont be used for tag names)

I don't do so?! What exactly do you mean ... ?

**Comment by hrbu** [comment]
> Downloaded coder-template has the manifest with upper case name MANIFEST:

I changed the names several times. Think the issue is caused by git as it does not detects case changes.

**Comment by edwingamboa** [comment]
> I don't do so?! What exactly do you mean ... ?

In the dist version of the components, in showrooms.html (Demos), the components are inserted as follows: 
In the images below, `elementName` is replaced as in second image:
![image](https://user-images.githubusercontent.com/5494773/48709878-c675c080-ebd4-11e8-834b-9d4bf57d1912.png)
![image](https://user-images.githubusercontent.com/5494773/48709826-a5ad6b00-ebd4-11e8-9fa1-a84eb6ed6f4f.png)

**Comment by hrbu** [comment]
... ha, got it. I added the scope without testing again.



_____________________________________

Hans-Dieter Böhlau
Geschäftsführer, Softwarearchitekt

GETrequest GmbH
Bauhausstr. 7c
D-99423 Weimar

M +49 159 0167 5467<tel:+49%20159%200167%205467>
boehlau@getrequest.de<mailto:boehlau@getrequest.de>
https://getrequest.de

Handelsregister: Amtsgericht Jena, HRB 514462
Geschäftsführer: Hans-Dieter Böhlau, Philipp Wagner


-------- Original message --------

**Comment by edwingamboa** [comment]
Exactly! :)

**Comment by hrbu** [comment]
@edwingamboa : Please check again ...

**Comment by edwingamboa** [comment]
@hrbu I tested once again and checked the things which are already solved. Also add some new issues
